# image: "pandoc/core"

# Run a Markdown linter
markmedown:
  stage: test
  image: registry.gitlab.com/06kellyjac/docker_markdownlint-cli:0.23.0-alpine
  script:
    - markdownlint .

# Convert the README to a PDF.
icanhazpdf:
  image: "auchida/markdown-pdf"
  stage: build
  script:
  - mkdir -p public
  - markdown-pdf -o public/readme.pdf README.md
  artifacts:
    paths:
    - public
  only:
    changes:
      - README.md
      - .gitlab-ci.yml

# Use pandoc to convert the README Markdown to HTMl with a test CSS file.
pages:
  image: "pandoc/core"
  stage: deploy
  needs: ["icanhazpdf","markmedown"]
  # CSS: https://benjam.info/panam/styling.css
  script:
  - mkdir -p public
  - cp web/styling.css public/
  - pandoc  --css=test.css      -s -f markdown+smart     --toc       --metadata pagetitle="[TEST] awesome ldap | GitLab.com/brie"                  --to=html5          README.md      -o public/index.html
  artifacts:
    paths:
    - public
  only:
    - test-css

# Use pandoc to convert the README to HTML.
pages:
  image: "pandoc/core"
  stage: deploy
  needs: ["icanhazpdf","markmedown"]
  # CSS: https://benjam.info/panam/styling.css
  script:
  - mkdir -p public
  - cp web/styling.css public/
  - pandoc  --css=styling.css      -s -f markdown+smart     --toc       --metadata pagetitle="awesome ldap | GitLab.com/brie"                  --to=html5          README.md      -o public/index.html
  artifacts:
    paths:
    - public
  only:
    changes:
      - README.md
      - .gitlab-ci.yml

# Deploy to droplet
droplets:
  environment: ldap.brie.ninja
  needs: ["icanhazpdf","markmedown"]
  stage: deploy
  when: manual
  script:
  - echo "Hello, world."
  only:
    - development
    - main