# image: "pandoc/core"

# Run a Markdown linter
markmedown:
  stage: test
  image: registry.gitlab.com/06kellyjac/docker_markdownlint-cli:0.23.0-alpine
  script:
    - markdownlint .

# Convert the README to a PDF.
icanhazpdf:
  image: "auchida/markdown-pdf"
  stage: build
  script:
  - mkdir -p public
  - markdown-pdf -o public/readme.pdf README.md
  artifacts:
    paths:
    - public
  only:
    changes:
      - README.md
      - .gitlab-ci.yml

# Use pandoc to convert the README to HTML.
pages:
  allow_failure: false
  environment:
    name: production
    url: https://ldap.brie.dev
  image: 
    name: "pandoc/core"
    entrypoint: [""]
  stage: deploy
  needs: ["icanhazpdf","markmedown"]
  # CSS: https://benjam.info/panam/styling.css
  script:
  - mkdir -p public
  - cp web/styling.css public/
  - pandoc --css=styling.css -s -f markdown --toc --metadata pagetitle="awesome ldap | GitLab.com/brie" --to=html5 README.md  -o public/index.html
  artifacts:
    paths:
    - public
  only:
    changes:
      - README.md
      - .gitlab-ci.yml
