# image: "pandoc/core"

icanhazpdf:
  image: "auchida/markdown-pdf"
  stage: build
  script:
  - mkdir -p public
  - markdown-pdf -o public/readme.pdf README.md
  artifacts:
    paths:
    - public

pandopages:
  image: "pandoc/core"
  stage: deploy
  script:
  - mkdir -p public
  - pandoc README.md -o public/index.html
  artifacts:
    paths:
    - public